# These are supported funding model platforms
github: ['knu' ,'deivid-rodriguez','envygeeks','flavorjones']
patreon: AleksandarDamnjanovic
open_collective: drblitz-weblab
ko_fi: jmjuanes
tidelift: python-pillow/Pillow 
community_bridge: crowdfunding
liberapay:  sowelisuwi 
issuehunt: JangirSumit
otechie: qubvel
lfx_crowdfunding: Jenkins funding
custom: ['https://github.com/jlord/sheetsee.js/issues/26	', 'https://github.com/jlord/sheetsee.js/commit/a5c3785ed8d6a35868bc169f07e40e889087fd2e','jlord@a5c3785ed8d6a35868bc169f07e40e889087fd2e']
